server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
#    url: jdbc:mysql://crud:3306/test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: pass
